### ISSUE TITLE
Getting labelled output

### ISSUE THREAD

**Issue by mfalcon** [CSAILVision/unifiedparsing#3]
Hi, I could succesfully run the ./demo_test.sh script but I don't know how to get the kind of output you show in the teaser image. For example: "wall is made of brick" or something similar.

Could you guide me through it?

**Comment by Tete-Xiao** [comment]
Hello,

This kind of relation needs to be calculated first. For example, after inferring an image, you can calculate what kind of objects is in the scene, and generate such descriptions.

Thanks,
